version: '3'
services:

  #PHP Service
  php_fpm:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: php_fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php_fpm
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: web_server
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      # - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-network
 
  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: your_laravel_db_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - laravel_dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-network

#Docker Networks
networks:
  laravel-network:
    driver: bridge

#Volumes
volumes:
  laravel_dbdata:
    driver: local