version: '3'
services:

  #PHP Service
  php_fpm:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: php_fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php_fpm
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      # - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-network

#Docker Networks
networks:
  laravel-network:
    driver: bridge